### ISSUE TITLE
dep ensure doesn't vendor all sigs.k8s.io/cluster-api files/packages

### ISSUE THREAD

**Issue by xmudrii** [davidewatson/cluster-api-provider-skeleton#4]
Hi there,

Thanks a lot for all the great work here and for this awesome project!

I used it to build a controller, but I got into the problem with `dep ensure`. Some packages from `sigs.k8s.io/cluster-api` repository were not vendored, causing the compilation of the controller to fail. Packages from other repositories were vendored successfully.

I was getting this error when trying to compile the `machine-controller`:
```
# sigs.k8s.io/cluster-api-provider-digitalocean/cloud/digitalocean/actuators/machine
../../cloud/digitalocean/actuators/machine/actuator.go:34:2: undefined: "sigs.k8s.io/cluster-api-provider-digitalocean/vendor/sigs.k8s.io/cluster-api/pkg/apis/cluster/common".RegisterClusterProvisioner
```
The project is while testing located in the `$GOPATH/sigs.k8s.io/cluster-api-provider-digitalocean` directory.

There were no any error when running `dep ensure` and everything looked normal.

In my case, I found out the `cluster-api/pkg/apis/cluster/common/plugins.go` file was not vendored causing the mentioned compilation failures.

I had luck resolving this by adding a following `prune` directive to the `Gopkg.toml` file:
```
[prune]
  go-tests = true
  unused-packages = true

  [[prune.project]]
    name = "sigs.k8s.io/cluster-api"
    unused-packages = false
```

Is this behavior as expected or the `Gopkg.toml` file should be updated? Is there potentially a better fix for this problem?

**Comment by davidewatson** [comment]
I suspect the vendored cluster-api needs to be updated. I will update it and verify.
